### ISSUE TITLE
build instruction

### ISSUE THREAD

**Issue by inkrement** [KashaMalaga/XiaomiMiBand#23]
please add build instructions.

**Comment by n1trux** [comment]
Apkstudio just gives me the error "Failed to recompile /path/to/folder/" but doesn't throw an error in console. How do I do that then?

**Comment by inkrement** [comment]
Maybe you have already the original app install. You have to remove this bevor installing the new one (the signatures will conflict). If you install it per console (adb install) you will get better error message!
