### ISSUE TITLE
How use this app?

### ISSUE THREAD

**Issue by piton4eg** [KashaMalaga/XiaomiMiBand#32]
Hi!
I found you app but I don't understand how to use this app. Could you help me? 
I have xiaomi mi2s, mi band, mac os. What I should do?

**Comment by colorprint** [comment]
You can compile the apk with android-apktool, sign it and install apk file after this...

**Comment by piton4eg** [comment]
@colorprint Could you help me to sign it?

**Comment by colorprint** [comment]
@piton4eg Check the last section "Signing Your App Manually" here: http://developer.android.com/tools/publishing/app-signing.html

**Comment by mircobabini** [comment]
Can you please provide a built apk once you signed it?

**Comment by colorprint** [comment]
Here is signed apk file: https://www.dropbox.com/s/yvw317yly3ne0fj/1.3.312_375.apk

**Comment by mircobabini** [comment]
thank you @colorprint (but it doesn't work), i get this error: "Parse error: There was a problem parsing the package." I'm on Android 4.2.2-

**Comment by mircobabini** [comment]
thank you @colorprint (but it doesn't work), i get this error: "Parse error: There was a problem parsing the package." I'm on Android 4.2.2.

**Comment by mircobabini** [comment]
Ok, probably it's because you built it with another min SDK. Through adb i got: Failure [INSTALL_FAILED_OLDER_SDK].

May you please sign a package built with API 17? Thanks you so much.

**Comment by mircobabini** [comment]
Ok, probably it's because you built it with another min SDK. Through adb i got: Failure [INSTALL_FAILED_OLDER_SDK].

May you please sign a package built with API 17? Thanks you so much.

**Comment by mircobabini** [comment]
Any news?

**Comment by colorprint** [comment]
I have build it as-is. May be there is minimal android version 4.3 or 4.4 required (that supports Bluetooth BLE)?

**Comment by piton4eg** [comment]
@colorprint thanks for apk. 
Does sending notifications from 3rd apps works for you? I tried to send messages to me in whatsapp, viber, vk and all of them didn't work. I selected these apps in "configuration notification" in Mi Band app. Maybe need to do something else?

**Comment by colorprint** [comment]
yes, it works.
notification permissions for this app should be enabled in android settings.

**Comment by piton4eg** [comment]
It's strange, because I gave all permissions for this app, and it didn't help me

**Comment by mircobabini** [comment]
Hi @colorprint, as written on the main repo page: "Patch for allow execution under Android 4.0+ instead 4.4", so i think it should exec even under 4.2.2. May you try to compile it with API 17? Thanks for your time, anyway.

**Comment by colorprint** [comment]
Here it is: https://dl.dropboxusercontent.com/u/4080500/Android/1.3.312_375_API17.apk

**Comment by mircobabini** [comment]
Thanks; still the same: "Parse error: There was a problem parsing the package.", don't really know way. Btw, thanks.

**Comment by KashaMalaga** [comment]
This project was a reverse engineering release from the Xiaomi apk.
Its not publish as java src, its smali. You can compile it, or donwnload from release section. You should need Java, Android SDK (21 using right now) and apktools or if you dont have many skills over there; use Apkstudio.

**Comment by piton4eg** [comment]
@colorprint thanks, it's works now! I don't know what was the reason of my problems.
@KashaMalaga thanks for release section, i didn't see it earlier

**Comment by piton4eg** [comment]
@KashaMalaga maybe can to add this information (about how to use) to readme?

**Comment by lele91enea** [comment]
I guys, where I can find the apk? I had the same problems of piton. Thanks a lot...

**Comment by lele91enea** [comment]
Hi guys, I have the same problems of mircobabini...how I can solve this problem? Thanks a lot!
