### ISSUE TITLE
Is Smart unlock is already there in current version?

### ISSUE THREAD

**Issue by vishnudevk** [KashaMalaga/XiaomiMiBand#33]
Patch to show Unlock Screen Feature without Miui device (Need Lollipop or MiuiSecurityBluetoothSettings Framework)?
I am using this feature in official play store MI Band app.

**Comment by KashaMalaga** [comment]
Dear vishnudevk,

We already did this patch before Xiaomi released his own method using SmarLock Lollipop Api ;)
