### ISSUE TITLE
Android 4.2.2 issue

### ISSUE THREAD

**Issue by mircobabini** [KashaMalaga/XiaomiMiBand#34]
I'm running on a Fairphone with Android 4.2.2. The phone supports BT le by specifics.

I tried all your releases: the 1.2 said my android version is too old, and the oldest 1.3 as well. The newest 1.3 and the latest 1.4 don't even install, providing the "error parsing package" error.

Any ideas? Thank you so much for your time.

**Comment by KashaMalaga** [comment]
There is no way, in the past I bypassed the app restrictions to allow install and run the app, but if there is no BLE API (witch means you need Android 4.3 or more). You couldnt sync with the band.
Read this: https://developer.android.com/guide/topics/connectivity/bluetooth-le.html

And in ur case: https://blog.matthiasbock.net/2014/10/20/bluetooth-low-energy-for-the-fairphone/

So u must to cook your own rom or looking for another phone. Sorry, but there is no more magic here

**Comment by mircobabini** [comment]
Thanks for explanation but you wrote that it has "Patch for allow execution under Android 4.0+ instead 4.4", so I think it should go over the "update your android" screen, no? Thanks, BTW.
