### ISSUE TITLE
1.4.152_1025 crashes

### ISSUE THREAD

**Issue by colorprint** [KashaMalaga/XiaomiMiBand#35]
1.4.152_1025 build apk installs fine but crashes when I try to open it.
Previous build works fine.
HTC One XL (HTC evita).

**Comment by KashaMalaga** [comment]
Log or didnt happen

**Comment by colorprint** [comment]
Here it is: https://dl.dropboxusercontent.com/u/4080500/logcat.txt

**Comment by KashaMalaga** [comment]
You have some troubles with db notifications from the extend module.
D/myLogs  (22954): local db doesn't exist

Clear your log file from your internal path mili_log.txt if its bigger than 10mb and remove notificationappbd (witch gives u this crash).

PS. Just tested under English and Spanish language, if still crash, complete the uninstall process.

**Comment by colorprint** [comment]
Thanks! It works now
