### ISSUE TITLE
Mi Smart Scale Support

### ISSUE THREAD

**Issue by apazga** [KashaMalaga/XiaomiMiBand#39]
Hola!

En las próximas releases se mantendrá desactivado el módulo de peso? :-S. Los que tenemos la Mi Smart Scale lo vamos a echar en falta... o tendremos que usar una versión distinta.

¿Sería posible compilar una versión adicional con ese módulo habilitado al menos?
## Gracias y buen trabajo!!!

Hi!

Next releases won't include the weigth module? :-S I need it for the Mi Smart Scale.
Is there any possibility to compile an additional version including this module?

Thanks and keep up the good work!

**Comment by KashaMalaga** [comment]
Hola Abel,

Tengo la version nueva desde el día que salío pero no la sincronicé con el repo, no hay problema en que existan ambas versiones, lo publicaré en un ratito.

Saludos

**Comment by apazga** [comment]
Gracias mil!! :+1:

**Comment by KashaMalaga** [comment]
Let me know if works fine.

https://github.com/KashaMalaga/XiaomiMiBand/releases/tag/1.4.925

**Comment by apazga** [comment]
Perfect, family added, Smart Scale & Mi Band paired, and everything is ok by now!

Thank you very much! ;) :+1:

**Comment by apazga** [comment]
Oops... Todo bien, pero tras la actualización de firmware que ha saltado, al volver a intentar utilizarla hoy ya no funcionaba :-S
No aparece nada en la pantalla al subirte a ella, y la aplicación tampoco la reconoce. Y no tiene botón de reset :-S

Puf... ¿Alguna sugerencia?

**Comment by KashaMalaga** [comment]
Dos horitas en el congelador y se le quitan las tonterias (no es broma)

**Comment by apazga** [comment]
OMG, y qué le hace el frío? Había visto cosas como utilizar el congelador para romper la encriptación del teléfono volcando la RAM justo después de sacarlo, pero la báscula... xD

**Comment by KashaMalaga** [comment]
Pensaba que te referías a la pulsera, en el caso de la báscula... no sé que comentarte, lleva el mismo firmware de casa original, cuando se actualizó por última vez, se completó correctamente y se reinicio, la misma? En caso de bloqueo deberás esperar a que se agote la batería o lo abrás y lo hagas manualmente..

**Comment by apazga** [comment]
La báscula actualizó su firmware ayer con el APK nuevo, y hoy no funcionaba (pero ayer correctamente).

Lleva pilas, 4 AA normales, y las he quitado, probado otras, pero nada :(
