### ISSUE TITLE
How To

### ISSUE THREAD

**Issue by KarinW** [KashaMalaga/XiaomiMiBand#41]
Hi,
how does your project work? I couldn't find the right directory to open in Android Studio (are there no activities etc?) or should i just use the apk file (tried that but the app shut down?!) Maybe you could drop a line on how to execute..
I would really love to have an Mi Fit App for Android < 4.4 and no Bluetooth 4.0!!
Thanks

**Comment by KashaMalaga** [comment]
This is a smali project so you should need another tools in case u want to compile the app (apkstoudio should be fine if you are a newbie). You could run app but you couldnt search without BLE support. Look under release path to donwload
